# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build: # job1 id
    runs-on: ubuntu-latest # 运行环境为最新版 Ubuntu
    name: A job to deploy blog.
    steps:
      - name: Checkout # step1 获取源码
        uses: actions/checkout@v1 # 使用 actions/checkout@v1
        with: # 条件
          submodules: true # Checkout private submodules(themes or something else). 当有子模块时切换分支？

      # Caching dependencies to speed up workflows. (GitHub will remove any cache entries that have not been accessed in over 7 days.) 缓存压缩 node_modules，不用每次下载，使用时解压，可以加快工作流的执行过程，超过 7 天没有使用将删除压缩包。
      - name: Cache node modules # step2
        uses: actions/cache@v1
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install Dependencies # step3 name
        if: steps.cache.outputs.cache-hit != 'true' # 如果变量 cache-hit 不等于 true
        run: npm install # 安装 node modules 相关依赖

      # Deploy hexo blog website.
      - name: Deploy # step4
        id: deploy
        uses: sma11black/hexo-action@v1.0.0
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          user_name: flyingliu
          user_email: liufeilai@gmail.com