# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Hexo Auto-Deploy by GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v1

      - name: 2. setup nodejs...
        uses: actions/setup-node@v1

      - name: 3. install hexo...
        run: |
          npm install hexo-cli -g
          npm install

      - name: 4. hexo generate public files...
        run: |
          hexo clean
          hexo g

      - name: 5. hexo deploy ...
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          git config --global user.name "flyingliu"
          git config --global user.email "liufeilai@gmail.com"
          git config --global core.quotepath false

          hexo d
